export function getEnumKey<T>(kvs: Record<string, T>, value: T): string | undefined {
	for (const key in kvs) {
		if (kvs[key] === value) return key;
	}
}

export type VFormats = typeof VFormats[keyof typeof VFormats];
export const VFormats = {
	RGBA8888: 0,
	ABGR8888: 1,
	RGB888: 2,
	BGR888: 3,
	RGB565: 4,
	I8: 5,
	IA88: 6,
	P8: 7,
	A8: 8,
	RGB888_BLUESCREEN: 9,
	BGR888_BLUESCREEN: 10,
	ARGB8888: 11,
	BGRA8888: 12,
	DXT1: 13,
	DXT3: 14,
	DXT5: 15,
	BGRX8888: 16,
	BGR565: 17,
	BGRX5551: 18,
	BGRA4444: 19,
	DXT1_ONEBITALPHA: 20,
	BGRA5551: 21,
	UV88: 22,
	UVWQ8888: 23,
	RGBA16161616F: 24,
	RGBA16161616: 25,
	UVLX8888: 26,
	R32F: 27,
	RGB323232F: 28,
	RGBA32323232F: 29,

	NV_NULL: 33, // 0 bpp
	ATI2N: 34, // Red, Green BC5 compressed format - 8 bpp
	ATI1N: 35, // Red BC4 compressed format - 4 bpp

	R8: 69,
	BC7: 70,
	BC6H: 71,
} as const;

export type VFlags = typeof VFlags[keyof typeof VFlags];
export const VFlags = {
	None:										0x0,
	PointSample:								0x00000001,
	Trilinear:									0x00000002,
	ClampS:										0x00000004,
	ClampT:										0x00000008,
	Anistrophic:								0x00000010,
	HintDXT5:									0x00000020,
	SRGB:										0x00000040, // Originally internal to VTex as TEXTUREFLAGS_NOCOMPRESS.
	DEPRECATED_NoCompress:						0x00000040,
	Normal:										0x00000080,
	NoMip:										0x00000100,
	NoLOD:										0x00000200,
	MinMip:										0x00000400,
	Procedural:									0x00000800,
	OneBitAlpha:								0x00001000, // Automatically generated by VTex.
	EightBitAlpha:								0x00002000, // Automatically generated by VTex.
	Envmap:										0x00004000,
	RenderTarget:								0x00008000,
	DepthRenderTarget:							0x00010000,
	NoDebugOverride:							0x00020000,
	SingleCopy:									0x00040000,
	UNUSED0:									0x00080000, // Originally internal to VTex as TEXTUREFLAGS_ONEOVERMIPLEVELINALPHA.
	DEPRECATED_OneOverMipLevelInAlpha:			0x00080000,
	UNUSED1:									0x00100000, // Originally internal to VTex as TEXTUREFLAGS_PREMULTCOLORBYONEOVERMIPLEVEL.
	DEPRECATED_PreMultColorByOneOverMipLevel:	0x00100000,
	UNUSED2:									0x00200000, // Originally internal to VTex as TEXTUREFLAGS_NORMALTODUDV.
	DEPRECATED_NormalToDuDv:					0x00200000,
	UNUSED3:									0x00400000, // Originally internal to VTex as TEXTUREFLAGS_ALPHATESTMIPGENERATION.
	DEPRECATED_AlphaTestMipGeneration:			0x00400000,
	NoDepthBuffer:								0x00800000,
	UNUSED4:									0x01000000, // Originally internal to VTex as TEXTUREFLAGS_NICEFILTERED.
	DEPRECATED_NiceFiltered:					0x01000000,
	ClampU:										0x02000000,
	VertexTexture:								0x04000000,
	SSBump:										0x08000000,
	UNUSED5:									0x10000000, // Originally TEXTUREFLAGS_UNFILTERABLE_OK.
	DEPRECATED_Unfilterable_OK:					0x10000000,
	BORDER:										0x20000000,
	DEPRECATED_SpecVar_Red:						0x40000000,
	DEPRECATED_SpecVar_Alpha:					0x80000000,
} as const;

export type VCompressionMethods = typeof VCompressionMethods[keyof typeof VCompressionMethods];
export const VCompressionMethods = {
	Deflate: 8,
	ZSTD: 93,
} as const;

export const NO_DATA = 0x2;
