export enum VFormats {
	RGBA8888 = 0,
	ABGR8888,
	RGB888,
	BGR888,
	RGB565,
	I8,
	IA88,
	P8,
	A8,
	RGB888_BLUESCREEN,
	BGR888_BLUESCREEN,
	ARGB8888,
	BGRA8888,
	DXT1,
	DXT3,
	DXT5,
	BGRX8888,
	BGR565,
	BGRX5551,
	BGRA4444,
	DXT1_ONEBITALPHA,
	BGRA5551,
	UV88,
	UVWQ8888,
	RGBA16161616F,
	RGBA16161616,
	UVLX8888,
	R32F,
	RGB323232F,
	RGBA32323232F,

	NV_NULL = 33,				// 0 bpp
	ATI2N,						// Red, Green BC5 compressed format - 8 bpp
	ATI1N,						// Red BC4 compressed format - 4 bpp
	
	IMAGE_FORMAT_BC7 = 70,
}

export enum VFlags {
	PointSample									= 0x00000001,
	Trilinear									= 0x00000002,
	ClampS										= 0x00000004,
	ClampT										= 0x00000008,
	Anistrophic									= 0x00000010,
	HintDXT5									= 0x00000020,
	SRGB										= 0x00000040, // Originally internal to VTex as TEXTUREFLAGS_NOCOMPRESS.
	DEPRECATED_NoCompress						= 0x00000040,
	Normal										= 0x00000080,
	NoMip										= 0x00000100,
	NoLOD										= 0x00000200,
	MinMip										= 0x00000400,
	Procedural									= 0x00000800,
	OneBitAlpha									= 0x00001000, // Automatically generated by VTex.
	EightBitAlpha								= 0x00002000, // Automatically generated by VTex.
	Envmap										= 0x00004000,
	RenderTarget								= 0x00008000,
	DepthRenderTarget							= 0x00010000,
	NoDebugOverride								= 0x00020000,
	SingleCopy									= 0x00040000,
	UNUSED0										= 0x00080000, // Originally internal to VTex as TEXTUREFLAGS_ONEOVERMIPLEVELINALPHA.
	DEPRECATED_OneOverMipLevelInAlpha			= 0x00080000,
	UNUSED1										= 0x00100000, // Originally internal to VTex as TEXTUREFLAGS_PREMULTCOLORBYONEOVERMIPLEVEL.
	DEPRECATED_PreMultColorByOneOverMipLevel	= 0x00100000,
	UNUSED2										= 0x00200000, // Originally internal to VTex as TEXTUREFLAGS_NORMALTODUDV.
	DEPRECATED_NormalToDuDv						= 0x00200000,
	UNUSED3										= 0x00400000, // Originally internal to VTex as TEXTUREFLAGS_ALPHATESTMIPGENERATION.
	DEPRECATED_AlphaTestMipGeneration			= 0x00400000,
	NoDepthBuffer								= 0x00800000,
	UNUSED4										= 0x01000000, // Originally internal to VTex as TEXTUREFLAGS_NICEFILTERED.
	DEPRECATED_NiceFiltered						= 0x01000000,
	ClampU										= 0x02000000,
	VertexTexture								= 0x04000000,
	SSBump										= 0x08000000,
	UNUSED5										= 0x10000000, // Originally TEXTUREFLAGS_UNFILTERABLE_OK.
	DEPRECATED_Unfilterable_OK					= 0x10000000,
	BORDER										= 0x20000000,
	DEPRECATED_SpecVar_Red						= 0x40000000,
	DEPRECATED_SpecVar_Alpha					= 0x80000000,
}
