name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup & Install
        uses: pnpm/setup@v2.0.2

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --access public

  publish_jsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup & Install
        uses: pnpm/setup@v2.0.2

      - name: Publish package
        run: pnpx jsr publish --allow-slow-types
